[project]
name = "dafna"
version = "0.1.0"
description = "Dafna package: search of DNA secondary structures via finite automata"
readme = "README.md"
requires-python = ">= 3.12"
license = { file = "LICENSE" }
authors = [
    { name = "Yurushkin M.V.", email = "m.yurushkin@gmail.com" },
    { name = "Gervich L.R." },
    { name = "Bachurin S.S." },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "rstr>=3.2.2",
    "graphviz>=0.20.3",
    "tqdm>=4.67.1",
    "numpy>=2.2.3",
    "regex>=2024.11.6",
]

[project.scripts]
dafna = "dafna.cli:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"dafna.lib" = ["*.so", "*.dll"]
